## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        hbm2ddl:
          auto: create
        generate-ddl: true
    show-sql: true
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platrform: postgres
    url: jdbc:postgresql://localhost:5432/postgres?searchpath = schema_name
    username: postgres
    password: 3418