## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        ddl-auto: update
    show-sql: true
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 3418
